# Generated by Django 5.1.1 on 2024-09-23 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('url_to_lesson', models.FileField(upload_to='lessons/files/', verbose_name='File')),
                ('duration', models.DurationField(blank=True, editable=False, null=True, verbose_name='Duration')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=128)),
                ('lastname', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Owner',
                'verbose_name_plural': 'Owner',
            },
        ),
        migrations.CreateModel(
            name='UserProductLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_duration', models.DurationField(verbose_name='View duration')),
                ('watched', models.BooleanField(default=False, verbose_name='Watched')),
            ],
            options={
                'verbose_name': 'User product lesson',
                'verbose_name_plural': 'User product lessons',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('lesson', models.ManyToManyField(related_name='products', to='products.lesson')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.owner')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ManyToManyField(related_name='user_products', to='products.lesson', verbose_name='Lesson')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_users', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'User Product',
                'verbose_name_plural': 'User Products',
            },
        ),
    ]
