# Generated by Django 5.1.1 on 2024-09-23 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_products', to='users.user', verbose_name='User'),
        ),
        migrations.AddField(
            model_name='userproductlesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_product_lessons', to='products.lesson', verbose_name='Lesson'),
        ),
        migrations.AddField(
            model_name='userproductlesson',
            name='user_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_product_lessons', to='products.userproduct', verbose_name='user_product_lessons'),
        ),
    ]
